### PR TITLE
Added support for URLs with ports and more protocols, closes #1

### LINKED ISSUE #1: URLs with port specifier are invalid
This package uses the dependency `is-url`. Unfortunately `is-url` does not correctly validate URLs with a port specifier.

The url `amqp://user:pass@domain.tld:1234` is validated as invalid, although it is a perfectly valid URL.

I know that this project hasn't been maintained since four years, but I wanted to save other people some trouble.

### PR DESCRIPTION
**Pull request by riker09**
As requested here's my take on supporting URLs with ports and protocols.

I had to update the mocha dependency. Committing the package-lock.json is good practise.

### CODE REVIEW

**Comment by zeke** [comment]
Thanks! Looks like tests are failing:

```
const spawn = require('child_process').spawn;
^^^^^
SyntaxError: Use of const in strict mode.
```

You can take out the strict mode.

**Comment by zeke** [comment]
Tests are still failing. There must be another `use strict` in the main file.

**Comment by riker09** [comment]
The only occurence of "strict" was within the test file. I don't have the ressources to fix the travis configuration. Given the age of this repo I assume that by upgrading the dependencies from Mocha v1.x to v5.x I did break something along the way.

Since I already have workaround in my project for redacting urls I do not consider this a high priority, tbh.

**Comment by zeke** [comment]
I opened https://github.com/zeke/redact-url/pull/3 as a replacement to this PR so I can make some changes.

**Pull request closed without merging**
